### ISSUE TITLE
Webpack "define cannot be used indirect"

### ISSUE THREAD

**Issue by nbwar** [doowb/set-getter#1]
When this library is imported via webpack it throws an error `define cannot be used indirect`
see: https://github.com/jonschlinkert/pretty-remarkable/issues/4

The issue seems to be you define a function called `define` which is a global function defined by webpack. The easy fix is to just rename that function

see: https://github.com/webpack/webpack/issues/2958

**Comment by jonschlinkert** [comment]
closing per the discussion on  jonschlinkert/pretty-remarkable#4. It was already established that this is very clearly a bug in webpack and not related to this module.
